name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest


    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: ./mars-expedition

    env:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      DB_PORT: 5432
      BACKEND_PORT: 8081
      BACKEND_URL: http://localhost:8081
      VITE_USERNAME: test
      VITE_PASSWORD: Rolad12!
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      CI: true


    steps:
      - name: Checkout Frontend Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend
        run: npm install

      - name: Checkout Backend Repo
        uses: actions/checkout@v3
        with:
          repository: UGTeamProject/mars-expedition-be
          path: backend

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start Backend in Background
        run: |
          ./gradlew bootRun &
          echo $! > backend_pid.txt
        working-directory: backend/expedition

      - name: Wait for Backend
        run: |
          echo "Waiting for backend"
          for i in {1..60}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/api || echo "000")
            if [ "$status" = "200" ] || [ "$status" = "403" ]; then
              echo "Backend is up! (HTTP $status)"
              exit 0
            fi
            echo "Waiting... ($i) - HTTP $status"
            sleep 2
          done
          echo "Backend did not start in time."
          exit 1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: mars-expedition/playwright-report/
          retention-days: 15

      - name: Stop Backend
        if: always()
        run: |
          if [ -f backend_pid.txt ]; then
            kill -9 $(cat backend_pid.txt) || true
          fi
