name: Ensure Formatting
on: [ pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        working-directory: ./mars-expedition/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        working-directory: ./mars-expedition/
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./mars-expedition/
        run: npm install

      - name: Run formatting check
        working-directory: ./mars-expedition/
        run: npm run format

      - name: Annotate Pull Request with Results
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Found formatting issues. Please run `npm run format:fix` to fix them.'
              })